### ISSUE TITLE
Projeto de interface - User Flow

### ISSUE THREAD

**Issue by FelipeAlvRodrigues** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e1-proj-web-t5-pmv-ads-2024-1-e1-projfocoacademico#8]

**Comment by rodrigo-pova** [comment]
@guicostak @damian-nestea @beatrice-arecippo @mauricioferreiradev @FelipeAlvRodrigues podemos encerrar essa? Acho que está pronto né?
